import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  mainContainer: {
  
  },
  iphone: {
    flex:1,
    marginTop:50,
    marginLeft:20
  },
  iconsArrowLeft: {
    // position: 'relative',
    // width: 41,
    // height: 27,
    // marginTop: 50,
    // marginLeft: 11,
    // backgroundImage: require('../assets/images/71fbde9e83631b7c873644c41822c92510c65306.png'),
    // zIndex: 32,
  },
  group1: {
    flexDirection:'row',
  },
  createAccount: {
    flex: 1,
    flexDirection:'column',
    position: 'absolute',
    color: '#000000',
    // fontFamily: 'Futura',
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 42.5,
  },
  download: {
    // position: 'absolute',
    // width: 58,
    // height: 40,
    // top: 3,
    // left: 237,
    // // backgroundImage: require('../assets/images/4f12bc2ef71369ca9e2eb76c7b9d5427db4fc466.png'),
    // zIndex: 15,
  },
  enterEmailPassword: {
    flexDirection: 'column',
    height: 19,
    color: '#616161',
    // fontFamily: 'Helvetica Neue',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19,
    textAlign: 'left',
    flexWrap: 'nowrap',
  },
  group2: {
    position: 'relative',
    width: 326,
    height: 75,
    marginTop: 20,
    fontSize: 0,
    zIndex: 17,
  },
  email: {
    flexDirection: 'column',
    position: 'relative',
    height: 18,
    margin: 0,
    color: '#000000',
    // fontFamily: 'Helvetica Neue',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 23,
  },
  group3: {
    position: 'relative',
    width: 326,
    height: 38,
    marginTop: 19,
    zIndex: 18,
  },
  rectangle: {
    position: 'absolute',
    width: 326,
    height: 38,
    top: 0,
    left: 0,
    backgroundColor: 'rgba(217, 217, 217, 0.3)',
    zIndex: 19,
    borderRadius: 10,
  },
  groupInput: {
    position: 'absolute',
    width: 326,
    height: 38,
    top: 0,
    left: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    zIndex: 22,
  },
  iconsEmail: {
    position: 'absolute',
    width: 24,
    height: 24,
    top: 7,
    left: 19,
    // backgroundImage: require('../assets/images/fb2dfa82e5bc6d89c8588c1a112f337e6a9cc2de.png'),
    opacity: 0.5,
    zIndex: 21,
  },
  email4: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'absolute',
    height: 19,
    top: 10,
    left: 54,
    color: '#808080',
    // fontFamily: 'Helvetica Neue',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 20,
  },
  group5: {
    position: 'relative',
    width: 326,
    height: 71,
    marginTop: 30,
    fontSize: 0,
    zIndex: 24,
  },
  password: {
    flexDirection: 'column',
    position: 'relative',
    height: 18,
    margin: 0,
    color: '#000000',
    // fontFamily: 'Helvetica Neue',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 18,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 31,
  },
  group6: {
    position: 'relative',
    width: 326,
    height: 38,
    marginTop: 15,
    zIndex: 25,
  },
  rectangle7: {
    position: 'absolute',
    width: 326,
    height: 38,
    top: 0,
    left: 0,
    backgroundColor: 'rgba(217, 217, 217, 0.3)',
    zIndex: 26,
    borderRadius: 10,
  },
  groupInput8: {
    position: 'absolute',
    width: 326,
    height: 38,
    top: 0,
    left: 0,
    backgroundColor: 'transparent',
    borderWidth: 0,
    zIndex: 30,
  },
  iconsLock: {
    position: 'absolute',
    width: 23,
    height: 23,
    top: 6,
    left: 19,
    // backgroundImage: require('../assets/images/3d105aae824bc61086e504800df2db6b9c06b535.png'),
    opacity: 0.5,
    zIndex: 29,
  },
  password9: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'absolute',
    height: 19,
    top: 10,
    left: 54,
    color: '#808080',
    // fontFamily: 'Helvetica Neue',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 27,
  },
  iconsHidden: {
    position: 'absolute',
    width: 27,
    height: 19,
    top: 10,
    left: 290,
    // backgroundImage: require('../assets/images/dda916e7e512991ae736f79394cf9e256e255b81.png'),
    opacity: 0.5,
    zIndex: 28,
  },
  groupA: {
    position: 'relative',
    width: 273,
    height: 21,
    marginTop: 45,
    zIndex: 2,
    borderRadius: 5,
  },
  termsPolicy: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'absolute',
    height: 21,
    top: 0,
    left: 168,
    color: '#febb1d',
    // fontFamily: 'Futura',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 3,
  },
  agreeSplitify: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    position: 'absolute',
    height: 21,
    top: 0,
    left: 39,
    color: '#000000',
    // fontFamily: 'Futura',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 4,
  },
  rectangleB: {
    position: 'absolute',
    width: 23,
    height: 20,
    top: 0,
    left: 0,
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderColor: '#fed470',
    zIndex: 5,
    borderRadius: 5,
  },
  groupC: {
    position: 'relative',
    width: 333,
    height: 236.988,
    marginTop: 19,
    marginLeft: 27,
    zIndex: 6,
  },
  line: {
    position: 'relative',
    width: 333.003,
    height: 1.988,
    marginTop: -1,
    // backgroundImage: require('../assets/images/fde68dcd-b44e-4da2-ae2d-05c5d6afeb81.png'),
    zIndex: 10,
  },
  flexRowDb: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    width: 247,
    height: 21,
    marginTop: 37,
    zIndex: 9,
  },
  alreadyHaveAccount: {
    flexShrink: 0,
    position: 'relative',
    height: 21,
    color: '#000000',
    // fontFamily: 'Futura',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 8,
  },
  signIn: {
    flexShrink: 0,
    position: 'relative',
    height: 21,
    color: '#febb1d',
    // fontFamily: 'Futura',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
    textAlign: 'left',
    flexWrap: 'nowrap',
    zIndex: 9,
  },
  lineD: {
    position: 'relative',
    width: 333.003,
    marginTop: 176,
    // backgroundImage: require('../assets/images/99a2e97d-a4a9-4a10-b5c0-abac10eecd8c.png'),
    zIndex: 7,
  },
  buttonGroup: {
    height: 41,
    fontSize: 0,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative', // Ensure relative positioning for absolute children
    
    
  },
  signUp: {
    flexDirection: 'column',
    marginTop: 10, 
    color: '#000000',
    // fontFamily: 'Futura',
    position: 'absolute',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 21,
    flexWrap: 'nowrap',
    zIndex: 13,
  },
  rectangleE: {
    position: 'absolute',
    width: 320,
    height: 41,
    top: 0,
    left: 10,
    backgroundColor: '#febb1b',
    zIndex: 12,
    borderRadius: 20,
    alignItems: 'center',
  },
});
